// Generated by CoffeeScript 2.4.1
var fromMinutes, isAbsolute, splitByLine, toMinutes;

splitByLine = function(s) {
  if (s.length === 0) {
    return s;
  }
  return s.replace(/\r\n|\n\r|\r/g, '\n').split('\n');
};

toMinutes = function(t) {
  var m;
  if (t.length === 0) {
    return 0;
  }
  m = t.match(/\d+/g);
  if (m == null) {
    return 0;
  } else if (m.length === 1) {
    return parseInt(m[0]);
  } else {
    return parseInt(m[0]) * 60 + parseInt(m[1]);
  }
};

fromMinutes = function(m) {
  return ("00" + Math.floor(m / 60)).slice(-2) + ":" + ("00" + m % 60).slice(-2);
};

isAbsolute = function(t) {
  return t.trim().match(/^[^\d]/);
};

$(function() {
  var $csv, $input, $label, $output;
  $input = $("#input");
  $output = $("#output");
  $label = $("#label");
  $csv = $("#csv");
  return $input.bind("input", function(e) {
    var absStr, csvline, csvtext, head, i, j, labels, len, len1, line, linenum, m, outline, outtext, ref, ref1, time, wholeInMinutes;
    wholeInMinutes = 0;
    outtext = [];
    csvtext = [];
    labels = splitByLine($label.val().trimEnd());
    ref = splitByLine(($(this)).val().trimEnd());
    for (linenum = i = 0, len = ref.length; i < len; linenum = ++i) {
      line = ref[linenum];
      outline = [];
      absStr = "";
      if (line.length === 0) {
        outtext.push("");
        csvtext.push('"' + labels[linenum] + '", "", ""');
        continue;
      }
      ref1 = line.split(',');
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        time = ref1[j];
        m = toMinutes(time);
        absStr = isAbsolute(time);
        if (absStr) {
          wholeInMinutes = m;
        } else {
          wholeInMinutes += m;
        }
        outline.push(fromMinutes(wholeInMinutes));
      }
      outtext.push(outline.join(', '));
      csvline = [];
      csvline.push('"' + labels[linenum] + '"');
      if (outline.length === 0) {
        csvline.push('""');
        csvline.push('""');
      } else if (outline.length === 1) {
        head = (absStr ? absStr[0].toUpperCase() : 'P');
        if (labels.length <= linenum + 1 || head === 'R') {
          csvline.push('"R' + outline[0] + '"');
          csvline.push('""');
        } else if (head === 'S') {
          csvline.push('""');
          csvline.push('"S' + outline[0] + '"');
        } else {
          csvline.push('"P' + outline[0] + '"');
          csvline.push('""');
        }
      } else {
        csvline.push('"R' + outline[0] + '"');
        csvline.push('"S' + outline[1] + '"');
      }
      csvtext.push(csvline.join(', '));
    }
    $output.val(outtext.join('\n'));
    return $csv.val(csvtext.join('\n'));
  });
});
